# Generated by Django 4.0.6 on 2023-08-30 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_specification_post_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='specifications',
        ),
        migrations.AddField(
            model_name='specification',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.post'),
            preserve_default=False,
        ),
    ]
