# Generated by Django 4.0.6 on 2023-08-30 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_post_specifications_specification_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.post'),
        ),
    ]
