# Generated by Django 4.0.6 on 2023-08-30 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_specification_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post'),
        ),
    ]
